---
# tasks file for roles/app_setup

- name: Start Docker container for Spring Boot application
  docker_container:
    name: tp1_backend_1
    image: tiblouk/tp-devops-simple-api
    env:
      DB_HOST: "{{ DB_HOST }}"
      DB_PORT: "{{ DB_PORT | string }}"
      DB_NAME: "{{ DB_NAME }}"
      DB_USERNAME: "{{ DB_USERNAME }}"
      DB_PASSWORD: "{{ DB_PASSWORD }}"
    networks:
      - name: my-network