---
# tasks file for roles/front
- name: Start Front container
  docker_container:
    name: front
    image: tiblouk/tp-devops-front
    ports:
      - "1589:80"
    networks:
      - name: my-network
