# Définition du nom du workflow
name: CI CD

on:
  workflow_run:
    workflows: ["CI devops"] # Nom du workflow à surveiller
    types:
      - completed
  release:
    types: [published]
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible playbook
        run: ansible-playbook -i inventories/setup.yml playbook.yml
