name: CI devops 2023

on:
  push:
    branches: # TODO: Add branches to trigger this job
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build and test with Maven
        run: mvn clean verify
